name: GCN2
loop: true
normalize: true
architecture:
  num_layers: 16
  hidden_channels: 256
  alpha: 0.5
  dropout: 0.1
  batch_norm: true
  residual: true
  shared_weights: false
  drop_input: true
use_custom_loss: true
grad_norm: 0.5
optim: adam
adjust_lr: false
use_labels: false
lr: 0.001
epochs: 1000
log_steps: 1