name: GCN
norm: true
loop: true

params:
  reddit:
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.5
      drop_input: false
      batch_norm: true
      residual: false
    optim: adam
    lr: 0.01
    epochs: 400

  flickr:
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.3
      drop_input: false
      batch_norm: true
      residual: false
    optim: adam
    lr: 0.01
    epochs: 400

  yelp:
    arch_name: GCN
    architecture:
      num_layers: 2
      hidden_channels: 512
      dropout: 0.1
      drop_input: false
      batch_norm: true
      residual: false
    optim: adam
    lr: 0.01
    epochs: 500