name: GCN2
loop: true
norm: true

params:
  reddit:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400

  flickr:
    arch_name: GCN2
    architecture:
      num_layers: 8
      hidden_channels: 256
      dropout: 0.5
      drop_input: true
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.1
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 400

  yelp:
    arch_name: GCN2
    architecture:
      num_layers: 4
      hidden_channels: 512
      dropout: 0.0
      drop_input: false
      batch_norm: true
      residual: false
      shared_weights: false
      alpha: 0.2
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 500